spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PMS?characterEncoding=UTF-8
    username: root
    password: ~
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        event:
          merge:
            entity_copy_observer: allow
        enable_lazy_load_no_trans: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
upload:
  path: g://tmp//
  access-path: images/upload/